### ISSUE TITLE
It's tested? It works?

### ISSUE THREAD

**Issue by DLopezGo90** [mattyams/arisutea-pcb-rgb#1]
Hi bro, I'm considering building this keyboard

It's tested right?

**Comment by mattyams** [comment]
v0.3 has been tested and working great. I have v0.4 sitting here but real life got in the way and I wasn't able to build it, I will soon. There is no reason v0.4 shouldn't work as I only added a few more LEDs to the edge in that version.

**Comment by DLopezGo90** [comment]
Hey bro I want my build to look like this:

![image](https://user-images.githubusercontent.com/59780264/141671790-ef1fe16f-ff8a-480c-958f-09a89dc37872.png)

I want to build it only using frosted acrylic plates. I was thinking about doing something like this:

![image](https://user-images.githubusercontent.com/59780264/141673474-9552969c-d01f-4e74-b018-698bef8a142d.png)

What do you think about this?

**Comment by mattyams** [comment]
Should work out fine. I have a similar build that I did but not with this particular PCB and opal acrylic instead of frosted. See attached:
![20210413_215241](https://user-images.githubusercontent.com/16708009/141695358-0d345d44-0fd1-4186-a506-78e952c9315e.jpg)

**Comment by DLopezGo90** [comment]
Hey bro how many acrylic plates are part of that case? 3 or 4?

**Comment by mattyams** [comment]
In the one pictured there are 22 pieces total. This is because the parts for the inner case are broken out to 4 pieces to keep plastic waste to a minimum.
